name: Build and deploy
# This workflow is triggered on pushes to the repository.
on: [push]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    name: Build document
    # This job runs on Linux
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/jacarte/latex-build:latest27
      credentials:
        username: jacarte
        password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build document
        run: |
          apt-get update
          apt-get install -y curl
          pdflatex -draftmode  -interaction=nonstopmode -shell-escape Kappa.tex || true
          sleep 10
          bibtex Kappa || true
          sleep 10
          pdflatex -shell-escape -interaction=nonstopmode Kappa.tex || true
          sleep 30

          #pip3 install pikepdf
          # Check later
          # python3 usab/fix_index.py Kappa.pdf usab/kappa.pdf Lic.index.pdf
          cp Kappa.pdf Kappa.nocontrib.pdf
        env:
          ADDCONTRIB: "False"  

      # If the build works, do the spell check
      - name: Split by chapter
        run: |
          mkdir -p kappa_chapters
          python3 build_images/split_document.py Kappa.nocontrib.pdf kappa_chapters
      
      - name: Build document
        run: |
          pdflatex -draftmode -interaction=nonstopmode -shell-escape Kappa.tex || true
          sleep 5
          bibtex Kappa || true
          sleep 5
          pdflatex -shell-escape -interaction=nonstopmode Kappa.tex || true
          sleep 5

          # Fix with usasb
          #pip3 install pikepdf
          #cp Lic.pdf Lic.pdf.bck
          #rm Lic.pdf
          # python3 usab/fix_index.py Lic.pdf.bck usab/kappa.pdf Lic.index.pdf
          cp Kappa.pdf Kappa.contrib.pdf
        env:
          ADDCONTRIB: "True" 

      - name: Deploy document
        run: |
          
          cp Kappa.nocontrib.pdf /Kappa.nocontrib.pdf
          cp Kappa.contrib.pdf /Kappa.pdf
          cp -r kappa_chapters /kappa_chapters

          cd /
          git clone https://${{secrets.REPO_KEY2}}@github.com/Jacarte/jacarte.github.io jacartepage
          cd jacartepage
          cp /Kappa.pdf assets/pdf/thesis/Kappa.pdf
          cp /Kappa.nocontrib.pdf assets/pdf/thesis/Kappa.nocontrib.pdf
          cp -r -p /kappa_chapters assets/pdf/thesis
          
          git config --global user.email "xppcoder@gmail.com"
          git config --global user.name "jacarte"
          git config --global credential.helper cache

          git add .
          git commit -m "Automatic deploy from thesis repo"
          git push

          # The action on the page will automatically deploy the documents
        env:
          REPO_KEY: '${{ secrets.REPO_KEY2 }}'
      - name: Send notification
        run: |
          T="Deploy done at https://www.jacarte.me/assets/pdf/thesis/Kappa.pdf"
          curl --data parse_mode=HTML --data chat_id="665043934" --data "text=$T" "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage"
        env:
          BOT_API_TOKEN: '${{secrets.BOT_API_TOKEN}}'

