name: Spell checking
# This workflow is triggered on pushes to the repository.
on: [push]

  
jobs:
  build:
    name: Spell checking
    # This job runs on Linux
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/jacarte/latex-build:latest27
      credentials:
        username: jacarte
        password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build document
        run: |
          apt-get update
          apt-get install -y curl
          pdflatex -interaction=nonstopmode -shell-escape Kappa.tex || true
          sleep 30
          bibtex Kappa.aux || true
          sleep 30
          pdflatex -shell-escape -interaction=nonstopmode Kappa.tex || true
          sleep 15
          pdflatex -shell-escape -interaction=nonstopmode Kappa.tex || true
          sleep 15
        env:
          ADDCONTRIB: "False"  
          # Avoid widows, this helps the OCR for preventing the "CASING" error
          NOWIDOW: "True"
      
      - name: Upload assets to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kappa.pdf 
          path: Kappa.pdf 

      - name: Spell checking report
        run: |
          mkdir -p ./build_images/rois
          pip3 install readability happytransformer
          python3 ./build_images/ocr_spell_check.py Kappa.pdf dico.text
        env:
          TOKENIZERS_PARALLELISM: False
        
      - name: GIT
        run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"


      - name: Annotate new pdf on a new branch
        run: |
          git config --global --add safe.directory /__w/Kappa/Kappa
          ls -R .
          
          cp -r ./build_images/rois ./rois
          cp ./build_images/report.json ./report.json

          python3 ./build_images/create_html_report.py report.json index.html

          

          git rm -rf . && git checkout -b gh-pages
          git add rois index.html report.json && git commit -m 'Spell check report' 
          git push origin gh-pages --force
        env:
          REPO_KEY: '${{ secrets.REPO_KEY2 }}'


      - name: Send notification
        run: |
          T="Spell checking at http://www.jacarte.me/Kappa/"
          curl --data parse_mode=HTML --data chat_id="665043934" --data "text=$T" "https://api.telegram.org/bot${{secrets.BOT_API_TOKEN}}/sendMessage"
        env:
          BOT_API_TOKEN: '${{secrets.BOT_API_TOKEN}}'